GREEN-42 add gasUsed and transaction root for returned block data
shardeum/json-rpc-server pull request #15
Opened 2024-04-24 11:24 UTC by tonititi

Add block gasUsed and transaction root to the returned block data

2024-04-28 17:23 UTC, justin-shardeum commented on src/external/Collector.ts
> +      resultBlock.transactionsRoot = await this.calculateTransactionRoot(readableBlock.tranactions)
readableBlock.tranactions <-- appears to have a typo here.  Should be "transactions"?

2024-04-28 17:25 UTC, justin-shardeum commented on package.json
> +    "merkle-patricia-tree": "^4.2.4",
Will this still work without the "^"?  I remember in our group code review, we said we'd prefer not to have it.

2024-04-28 17:26 UTC, mhanson-github requested changes, later dismissed
Remove ^ in version.

Address other issue with misspelled parameter.

Retest

2024-04-28 17:26 UTC, mhanson-github commented on package.json
> +    "merkle-patricia-tree": "^4.2.4",
Remove carat in version.

2024-04-28 17:26 UTC, mhanson-github commented on src/external/Collector.ts
> +      resultBlock.transactionsRoot = await this.calculateTransactionRoot(readableBlock.tranactions)
This appears to be misspelled.  Am not sure how this could have worked.

2024-04-28 19:04 UTC, afostr commented
~/shardus/npm-release/json-rpc-server$ npm run compile

> shardeum-json-rpc@1.0.0 compile
> tsc -p .

src/external/Collector.ts:20:27 - error TS2307: Cannot find module 'ethers' or its corresponding type declarations.

20 import { BigNumber } from 'ethers'
                             ~~~~~~~~


Found 1 error.

2024-04-28 19:06 UTC, afostr requested changes, later dismissed
build does not compile
~/shardus/npm-release/json-rpc-server$ npm run compile

> shardeum-json-rpc@1.0.0 compile
> tsc -p .

src/external/Collector.ts:20:27 - error TS2307: Cannot find module 'ethers' or its corresponding type declarations.

20 import { BigNumber } from 'ethers'
                             ~~~~~~~~


Found 1 error.

2024-05-13 17:06 UTC, jairajdev commented on src/external/Collector.ts
> +import { BigNumber } from 'ethers'
Looks like the import lib has to be `@ethersproject/bignumber`

2024-05-13 17:09 UTC, jairajdev commented on src/external/Collector.ts
> +  async calculateTransactionRoot(txns: String[]): Promise<String> {
I think the correct type has to be `string`

2024-05-21 08:10 UTC, tonititi commented
By changing the command npm ci to npm i in both smoke tests 10+10 and 25+5, these two tests were passed

25+5: https://devs-work.shardeum.org/job/Testing/job/Smoke/job/work_in_progress/job/wip_green_25_plus_5/2/
10+10: https://devs-work.shardeum.org/job/Testing/job/Smoke/job/work_in_progress/job/wip_test_green_team/2/

2024-05-31 16:14 UTC, jairajdev approved these changes, later dismissed

2024-06-06 16:36 UTC, jairajdev approved these changes

2024-06-06 16:36 UTC, merged