Fix log endpoint auth
shardeum/json-rpc-server pull request #40
Opened 2024-07-04 01:22 UTC by asyed94

Adds the same auth to log stats endpoint on json-rpc-server as debug endpoints on shardeum validators.

2024-07-22 02:01 UTC, chrypnotoad commented
@CodiumAI-Agent /review

2024-07-22 02:02 UTC, CodiumAI-Agent commented
## PR Reviewer Guide 🔍

<table>
<tr><td>⏱️&nbsp;<strong>Estimated effort to review</strong>: 4 🔵🔵🔵🔵⚪</td></tr>
<tr><td>🧪&nbsp;<strong>No relevant tests</strong></td></tr>
<tr><td>🔒&nbsp;<strong>Security concerns</strong><br><br>

<strong>Sensitive information exposure:</strong><br> The PR includes hardcoded sensitive defaults for `passphrase` and `secret_key` in `src/config.ts`. This could lead to unintentional use of these defaults in production, posing a significant security risk.</td></tr>
<tr><td>⚡&nbsp;<strong>Key issues to review</strong><br><br>

<a href='https://github.com/shardeum/json-rpc-server/pull/40/files#diff-c3095d5010e65c52737a98a5d618ea24049ebe90c8470752426081d70ed6e012R169-R170'><strong>Sensitive Information</strong></a><br>The default passphrase and secret key are hardcoded in the configuration, which could lead to security risks if these defaults are used in production environments.

<a href='https://github.com/shardeum/json-rpc-server/pull/40/files#diff-7bc1140e724e284ae22084e1172568baa8d151063d02c75ed1d8805fa7796acaR57-R57'><strong>Error Handling</strong></a><br>The error handling in the `saveInterfaceStat` function logs the error but does not handle it further, which might lead to unhandled exceptions affecting the application's stability.

<a href='https://github.com/shardeum/json-rpc-server/pull/40/files#diff-b6b8de76e74cbbdd95a70e4ac764d9e83b15decaa8b4602ab1c6be306fc618f0R52-R53'><strong>Security Concern</strong></a><br>The `handleDebugAuth` function uses a counter to prevent replay attacks, but it relies on incrementing a variable that could be manipulated or reset, potentially allowing bypass of security checks.

</td></tr>
</table>

2024-07-22 15:23 UTC, chrypnotoad commented
depending on merge order this is going to require changes to the (not yet merged) jest tests #43

2024-08-26 15:18 UTC, chrypnotoad requested changes

2024-08-26 15:18 UTC, chrypnotoad commented on src/middlewares/debugMiddleware.ts
> +    }
do we need these other else's here? Is this unfinished or was this in progress stuff that needs to be deleted?

2024-08-26 15:18 UTC, chrypnotoad commented on src/routes/log.ts
> +    return res.json({ message: 'Interface stats recording disabled' }).status(304)
304 status code is really intended to indicate the resource hasn't changed generally around caching. 
I think 200 OK or 204 No Content would make more sense

2024-08-27 14:53 UTC, chrypnotoad requested changes

2024-08-27 14:53 UTC, chrypnotoad commented on src/routes/log.ts
> +import { debug_info, getInterfaceStatCounts } from '../logger'
this getInterfaceStatCounts does not exist

2024-08-27 14:53 UTC, chrypnotoad commented on src/routes/log.ts
> +})
I don't see this method mentioned in the readme. Look's like it was added in this PR and is calling a function that doesn't exist.

2024-08-27 14:55 UTC, chrypnotoad commented on src/types.ts
> +}
I copied this from `shardus-core` should we bring it in as a dependency instead?

2024-08-29 22:53 UTC, chrypnotoad commented on src/logger.ts
> -  /* eslint-enable security/detect-object-injection */
Was this intentionally removed?

2024-08-29 22:53 UTC, chrypnotoad commented on src/logger.ts
> -  /* eslint-disable security/detect-object-injection */
`apiPerfLogTicket[ticket]` causes the object-injection warning and is still used in this function, was this intentionally deleted?

2024-08-29 22:53 UTC, chrypnotoad commented on src/middlewares/debugMiddleware.ts
> +              //   /* prettier-ignore */ if (logFlags.verbose) console.log('Authorization failed for security level', authLevel)
```suggestion
```
delete unused log

2024-08-29 22:53 UTC, chrypnotoad commented on src/middlewares/debugMiddleware.ts
> +    // /* prettier-ignore */ if (logFlags.verbose) console.log('Error in handleDebugAuth:', error)
```suggestion
```
delete unused log

2024-08-30 16:53 UTC, chrypnotoad approved these changes, later dismissed

2024-09-03 19:26 UTC, mssabr01 requested changes

2024-09-03 19:26 UTC, mssabr01 commented on src/server.ts
> +  changeNode(ip, port)
This function can fail and this should be handled. The validation of the input is done in changeNode. If ip is not a valid IP address then nothing happens.

2024-09-03 19:26 UTC, mssabr01 commented on src/middlewares/debugMiddleware.ts
> +export function handleDebugAuth(_req: any, res: any, next: any, authLevel: any)
This middleware or the endpoints that call it need a rate limiter. See service points in the validator repo for example.

2024-09-04 02:58 UTC, mssabr01 submitted a review, later dismissed

2024-09-05 22:13 UTC, kun6fup4nd4 commented on src/middlewares/debugMiddleware.ts
> +        }
signing path w/o params is risky. in this exact implementation no vulnerability cuz of counter

2024-09-05 22:14 UTC, kun6fup4nd4 approved these changes, later dismissed

2024-09-07 01:06 UTC, chrypnotoad submitted a review, later dismissed

2024-09-07 18:21 UTC, chrypnotoad commented
@CodiumAI-Agent /review

2024-09-07 18:21 UTC, CodiumAI-Agent commented
**[Persistent review](https://github.com/shardeum/json-rpc-server/pull/40#issuecomment-2241905963)** updated to latest commit https://github.com/shardeum/json-rpc-server/commit/a766365150e06cddf1e53bf324b5ced13468f5e4

2024-09-09 15:37 UTC, chrypnotoad commented on src/server.ts
> +import { isIP, isIPv4 } from 'net';
```suggestion
import { isIPv4 } from 'net'; 
```
remove unused import

2024-09-09 15:37 UTC, chrypnotoad approved these changes, later dismissed

2024-09-09 15:56 UTC, timadinorth approved these changes

2024-09-09 18:45 UTC, kun6fup4nd4 submitted a review, later dismissed

2024-09-15 05:03 UTC, closed without merging

2024-09-15 05:03 UTC, CodiumAI-Agent commented
**[Persistent review](https://github.com/shardeum/json-rpc-server/pull/40#issuecomment-2241905963)** updated to latest commit https://github.com/shardeum/json-rpc-server/commit/6e50e6a7cafc21d80b3e8b540049d22c63aeff8f